### ISSUE TITLE
[DEP0005] DeprecationWarning: Buffer() is deprecated

### ISSUE THREAD

**Issue by jpogran** [hashicorp/js-releases#42]
Hey @BlackDark / @jpogran - I've been tracking an annoying deprecation warning I've been seeing in the https://github.com/hashicorp/setup-terraform GitHub Action recently.

```
(node:1617) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

This is actually seen in the opening screenshot 😄.

Tracking this back, it's been this change that's cause the message:

- Inclusion of `proxy-agent` package.
- This in-turn uses `pac-proxy-agent`
- This in-turn uses `get-uri`.
- This in-turn uses `ftp` (phew!)
- The (very old) `ftp` package makes use of `new Buffer()`: https://github.com/mscdex/node-ftp/pull/230

Got there!

I wonder if there is an alternative to the `proxy-agent` package?

_Originally posted by @magnetikonline in https://github.com/hashicorp/js-releases/issues/11#issuecomment-1112897963_

**Comment by magnetikonline** [comment]
Hey @jpogran - was able to deliver a fix here: https://github.com/hashicorp/js-releases/pull/43

Basically swapping out the `proxy-agent` package with the child `https-proxy-agent` package. Achieves the same result, but removes much of the package chain - including the offending `ftp` package.
