### ISSUE TITLE
`getReleases()` returns 404

### ISSUE THREAD

**Issue by michaellzc** [hashicorp/js-releases#45]
## Description

We started seeing [hashicorp/setup-terraform](https://github.com/hashicorp/setup-terraform) showing weird `404` error during action run, and we found this is coming from this library

## How to reproduce

https://runkit.com/exiasr/tf-is-broken

**Comment by michaellzc** [comment]
Okay..

re-run the script again and it works now.

is the https://releases.hashicorp.com API not stable?

**Comment by tabrath** [comment]
Just happened to me too, a couple of re-runs and it worked.

**Comment by michaellzc** [comment]
the release site was under maintenance.
