### ISSUE TITLE
Update openpgp dependency when fork is updated

### ISSUE THREAD

**Issue by LangdalP** [hashicorp/js-releases#6]
Hi.

I noticed an error during `npm install` of this package. The error is due to a transient dependency on https://github.com/openpgpjs/asmcrypto.js via https://github.com/vordimous/openpgpjs .

I have created a pull request in that repo (which is a fork of [openpgpjs/openpgpjs](https://github.com/openpgpjs/openpgpjs). [The pull request can be seen here](https://github.com/vordimous/openpgpjs/pull/1). I hope that once the owner of the repo accepts the pull request, you will update your dependency to a newer commit.

If the GitHub user vordimous is a Hashicorp employee, please take a look at the aforementioned pull request.

**Comment by LangdalP** [comment]
@aeschright 

An update: The GitHub userr vordimous has closed my pull request since he has said that he does not want to update/maintain his fork. This means that this error, which affects your package as well, cannot be fixed as long as it depends on his fork.

I am not sure how to proceed. An easy fix for you would be to instead depend on [my fork](https://github.com/LangdalP/openpgpjs), where I have added two commits on top of vordimous's fork. However, it might be preferable for you to either create your own fork to maintain greater control over your dependencies, or directly depend upon the official openpgpjs package once again.

For now, my team has resorted to depending on my fork of `js-releases`, where I am using my fork of `openpgpjs`.

**P.S:**
It seems I left out some details about the error in my initial text. If you want to reproduce it, first delete `node_modules` and do `npm cache clean --force`. Then try to `npm install` your package. You will then [be seeing this error](https://github.com/asmcrypto/asmcrypto.js/issues/178) if you have a recent version of node.

**Comment by geirsagberg** [comment]
@aeschright Awesome that this has been merged :) Could it be part of a patch release soon?

**Comment by jpogran** [comment]
Hi @geirsagberg, the changes discussed was released in v1.4.X and is currently available.

I have https://github.com/hashicorp/js-releases/pull/16 tracking updating to openpg v1.5.0 stable. Please watch that PR or comment there for any new questions.
